### DISCUSSION TITLE
Is it possible to specify a custom wrangler.toml when deploying?

### DISCUSSION THREAD

**Discussion by a4amaan** [cloudflare/wrangler-action#335] [Q&A] [answered]
I was trying to deploy to multiple cloudflare accounts with multiple wrangler files, but not sure if it is possible or not?

**Comment by jahands** [comment, marked as answer]
Hi! This is possible using a custom command:
```yaml
- name: Deploy
  uses: cloudflare/wrangler-action@v3
  with:
    command: deploy -c ./wrangler.toml
```
Here's a full example of what I tested with:
https://github.com/jahands/wrangler-action-example/blob/1026fa8ca3b02af178f22b585af502e5dda61533/.github/workflows/deploy.yml#L27
