### DISCUSSION TITLE
Deployment and alias URLs using Pages and Workers

### DISCUSSION THREAD

**Discussion by buberdds** [cloudflare/wrangler-action#370] [Q&A]
Hi, I am using wrangler-action with Pages as follows 
``` 
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: 
          accountId: 
          command: pages deploy <app-build-dir>  --project-name=<project-name> --branch ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || '' }}
```

and in a next workflow step I can grab `steps.deploy.outputs.deployment-url` (deployment URL with hash) and `steps.deploy.outputs.pages-deployment-alias-url` (stable URL for a branch)

samples:
Preview URL:	`https://<hash>.<project-name>.pages.dev/`
Alias: `https://<pr-number>.<project-name>.pages.dev/`

Now Cloudflare suggests to use Workers instead, but 
1) Deployment url does not support version https://github.com/cloudflare/wrangler-action/issues/302 so it behaves differently compared to Pages. It returns Worker URL, is this correct?
2) Workers don't provide aliases (in my case used to generate stable URLs for branches) at all. Is this true?

thanks for clarification :saluting_face:
