### ISSUE TITLE
build results in Unable to find authentication details.

### ISSUE THREAD

**Issue by hazcod** [cloudflare/wrangler-action#103]
Hi,

GitHub Action (`build.yml`):

```yaml
name: build

on:
  pull_request:

jobs:

  worker:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
    -
      name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
    -
      name: hugo build
      run: hugo --minify --gc --config=config.yml
    -
      name: wrangler
      uses: cloudflare/wrangler-action@2.0.0
      with:
        environment: prd
        command: build
```

Weirdly enough this results in the following:

```
Run cloudflare/wrangler-action@2.0.0
  with:
    environment: prd
    command: build

npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

added 101 packages, and audited 102 packages in 5s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Unable to find authentication details. Please pass in an 'apiToken' as an input to the action, or a legacy 'apiKey' and 'email'.
````

Ref https://github.com/iron-security/website

**Comment by winstxnhdw** [comment]
Hey,

Did you forget to pass your credentials like so?

```yaml
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
```
