### ISSUE TITLE
Job Hanging

### ISSUE THREAD

**Issue by andrewmunro** [cloudflare/wrangler-action#110]
My publish job has started hanging indefinitely when using this action...

![image](https://github.com/cloudflare/wrangler-action/assets/1107388/ee9e26dd-d9b0-4d9c-9e9c-c6851e1779c2)

It could be an issue with the runner maybe as I'm using a self-hosted runner with https://github.com/actions/actions-runner-controller.

Figured I'd ask here if anyone else has encountered this...

**Comment by andrewmunro** [comment]
As a workaround, I've switched to the following:

```
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Publish app
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: npx -y wrangler pages publish --project-name=myproject ${{ steps.extract.outputs.destination }}
```
