### ISSUE TITLE
The action is slow (takes more than a minute)

### ISSUE THREAD

**Issue by rikhuijzer** [cloudflare/wrangler-action#114]
This action spins up a full Docker container, which makes it very slow.

One solution for readers of this issue is to just install `wrangler` from `npm` and use that. For example:

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      <YOUR PAGE BUILD STEPS>

      - run: npm install -g wrangler@3.4.0

      - if: github.ref == 'refs/heads/main'
        run: wrangler <YOUR COMMAND>
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
```

Here, replace `<YOUR COMMAND>` with your `wrangler` command and `<YOUR PAGE BUILD STEPS>` with your build steps.

This takes about 7 seconds instead of more than a minute.
