### ISSUE TITLE
errors on missing user

### ISSUE THREAD

**Issue by TownLake** [cloudflare/wrangler-action#12]
I have a Hugo static site I'm attempting to publish with this action. However, each time I try, I receive an error when it attempts to install cargo after my previous action builds the site.

I have my account email and API Key saved in GitHub secrets for the repo; I know that worked because of the success when publishing manually below.

In the example here using this action, my action yams file contains:
```
name: Deploy to Workers

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Install Hugo
        run: sudo snap install hugo

      - name: Build
        run: hugo

      - name: Publish
        uses: cloudflare/wrangler-action@1.0.0
        with:
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}
```

Every time, that results in this error:

```
Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.6.0/x86_64-unknown-linux-musl
46
Wrangler has been installed!
47
+ @cloudflare/wrangler@1.6.0
48
added 27 packages from 13 contributors in 1.573s
49
 Using namespace for Workers Site "__oldblog-samrhea-workers_sites_assets"
50
 Success
51
⬇️ Installing cargo-generate...
52
 Creating project called `workers-site`...
53
Error: could not determine the current user, please set $USER
54
Error: tried running command:
55
/github/workspace/.cache/.wrangler/cargo-generate-fc3c677afe428cb1/cargo-generate generate --git https://github.com/cloudflare/worker-sites-init --name workers-site --force
56
exited with exit code: 1
57
##[error]Docker run failed with exit code 1
```

When I run the wrangler steps manually, it works. Example yaml here:

```
name: Deploy to Workers

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Install Hugo
        run: sudo snap install hugo

      - name: Install Wrangler
        run: sudo npm i @cloudflare/wrangler -g

      - name: Build
        run: hugo

      - name: config wrangler
        run: CF_EMAIL=${{ secrets.CF_EMAIL }} CF_API_KEY=${{ secrets.CF_API_KEY }} wrangler publish
```

**Comment by AustinCorridor** [comment]
Wonder if chaining the actions modifies the Docker user:
/github/workspace - Note: GitHub Actions must be run by the default Docker user (root). Ensure your Dockerfile does not set the USER instruction, otherwise you will not be able to access GITHUB_WORKSPACE.

**Comment by evan-day** [comment]
I too experience this issue, but I'm not sure of a resolution. I'm doing a Jekyll build via Docker and taking the outputted directory as the input for the Workers Site.

**Comment by jjelev** [comment]
I created action for build and deploy which is very simple.
```yaml
name: Staging

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn lint
      - run: yarn build
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID_STAGING }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_STAGING }}
          GRANT_TYPE: password
      - uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: staging
```
I see experienced this:
>  Installing cargo-generate...
 Creating project called `workers-site`...
Error: could not determine the current user, please set $USER
Error: tried running command:
/github/workspace/.cache/.wrangler/cargo-generate-fc3c677afe428cb1/cargo-generate generate --git https://github.com/cloudflare/worker-sites-init --name workers-site --force
exited with exit code: 1

But when I run wrangler locally I see this:

> ⬇️ Installing cargo-generate...
 Creating project called `workers-site`...
 Done! New project created *****/workers-site
added 2 packages from 2 contributors and audited 2 packages in 1.159s
found 0 vulnerabilities
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
 Built successfully, built project size is 11 KiB.
 Successfully published your script to *****

**Comment by jjelev** [comment]
It works with setting environment variable $USER. I am not sure if it should be root but it works with this just fine.
```yaml
      - uses: cloudflare/wrangler-action@1.1.0
        env:
          USER: root
```
Looking for your comments.
