### ISSUE TITLE
Installing private dependencies from a private NPM Registry?

### ISSUE THREAD

**Issue by p-j** [cloudflare/wrangler-action#13]
Hi there,

I'm trying to set up the wrangler action on one of our repository to automatically publish our workers.
I'm hitting a wall as we rely on a [Verdaccio](https://github.com/verdaccio/verdaccio) instance to host some private dependencies that we make use of in the worker.

Is there a way for me to set this up?

Here is a shortened version of our workflow that would reproduce the issue:

```yaml
name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Setup Private Registry
        run: |
          npm config set https://registry.eatwith.io/:_authToken "$GITHUB_OAUTH_TOKEN"
          npm config set https://registry.eatwith.io/:always-auth true
          npm config set registry https://registry.eatwith.io
          yarn config set https://registry.eatwith.io/:_authToken "$GITHUB_OAUTH_TOKEN"
          yarn config set https://registry.eatwith.io/:always-auth true
          yarn config set registry https://registry.eatwith.io
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - name: Create .env file before build
        run: |
          touch .env
          echo "SECRET_VAR=${{secrets.SECRET_VAR}}" >> .env
          echo "OTHER_SECRET=${{secrets.OTHER_SECRET}}" >> .env
      - name: Publish to production
        uses: cloudflare/wrangler-action@1.0.0
        with:
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}
          environment: 'production'
```

Is there a way to support a similar configuration?
Based on https://github.com/cloudflare/wrangler-action/blob/master/entrypoint.sh it seems there is no way currently for me to modify the NPM's configuration that is used when running `wrangler publish` is this something you would be interested in supporting?

**Comment by p-j** [comment]
FYI we fixed that by not using this action and installing wrangler as part of the build process in our workflow.

**Comment by signalnerve** [comment]
hey @p-j! sorry i missed this ticket originally - can you tell me more about your solution? the problem was around the action running `wrangler publish`, right? generally the action doesn't deal with dependencies, so if installing wrangler manually and managing it in your workflow was a fix, that's super interesting! would love to help solve this in the action if there's something i can do, let me know! 👍

**Comment by p-j** [comment]
Sorry @signalnerve I missed your message here.
I think we were falling into this case: https://github.com/cloudflare/wrangler/blob/79beb41f0ecf65e9f047e56f617393cff30e99af/src/commands/build/wranglerjs/mod.rs#L229-L259

Wrangler publish would run `npm install` as the `node_modules` aren't committed to the repository.

As part of getting this to run we've gone through multiple iterations and maybe we now have something that could be simplified a bit but here is what I came up with after some trial & error:

```yaml
name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup Private Repository
        run: |
          npm config set https://registry.eatwith.io/:_authToken "$GITHUB_OAUTH_TOKEN"
          npm config set https://registry.eatwith.io/:always-auth true
          npm config set registry https://registry.eatwith.io
          yarn config set https://registry.eatwith.io/:_authToken "$GITHUB_OAUTH_TOKEN"
          yarn config set https://registry.eatwith.io/:always-auth true
          yarn config set registry https://registry.eatwith.io
        env:
          GITHUB_OAUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.cache-name }}-
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install # install the dependencies with the registry config declared above, we've also added wrangler as a local dependency
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Retrieve node modules from cache
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.cache-name }}-
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-
      - name: Create .env file before build
        run: |
          touch .env
          echo "someEnvVar=${{ secrets.SOME_ENV_VAR }}" >> .env
          echo "anotherEnvVar=${{ secrets.ANOTHER_ENV_VAR }}" >> .env
      - name: Install global wrangler
        run: npm i -g @cloudflare/wrangler # global install of wrangler to ensure the ~/.wrangler folder is created correctly
      - name: Publish to preproduction
        run: yarn pub # runs wrangler publish using the local binary from node_modules/.bin/wrangler
        env:
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
```

It's probably overkill and maybe just installing the dependencies first and caching them would have been enough, at least based on wrangler's code highlighted above it should be.

So I guess it's just a matter of knowing/documenting that and/or having a way to configure the NPM env that will be used by wrangler if no node_modules is found.

I could probably also have gone with adding an extra step that would have created an `.npmrc` file with the config for the registry, instead of relying on global configuration.
