### ISSUE TITLE
v3 release currently broken

### ISSUE THREAD

**Issue by randomairborne** [cloudflare/wrangler-action#137]
[action + repo](https://github.com/randomairborne/speederboard/actions/runs/5813457248/job/15761064139) When trying to run the worker, iI get an "Error: Action Failed"

```
Run cloudflare/wrangler-action@v3
  with:
    apiToken: ***
    workingDirectory: cdn-upload-worker
    command: publish --env staging
📥 Installing Wrangler
  Running command: npm install wrangler@3.4.0
  npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
  ✅ Wrangler installed
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
🚀 Executing Wrangler Commands
  Error: 🚨 Action failed
  ```

**Comment by AlCalzone** [comment]
Maybe because the action is using wrangler v3, which doesn't have a `publish` command anymore, but `deploy`?
https://developers.cloudflare.com/workers/wrangler/commands/#deploy

**Comment by JacobMGEvans** [comment]
I should add `stderr` for more commands.

**Comment by JacobMGEvans** [comment]
Also a heads up with the new `wrangler-action` you should be able to consolidate these (once I figure out your bug) 
```
      - name: deploy prod & dev
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "cdn-upload-worker"
          command:  | 
             deploy --config wrangler.prod.toml
             deploy --config wrangler.toml
```
