### ISSUE TITLE
Post actions/cache@v1 fails because `.wrangler` is created for root:root

### ISSUE THREAD

**Issue by vpavlushkov** [cloudflare/wrangler-action#15]
We have a static web app deployed to Google cloud CDN and to be able to serve different versions we use a Cloudflare worker that maps between an original URL and folder name in the CDN bucket.

The worker config in the git repository is located next to the static page code, inside the `serve-index-worker`: 
```
repository
├── .github
│   ├── workflows                     <-- GitHub actions workflows
├── serve-index-worker
│   ├── .gitignore
│   ├── generate-worker.js
│   ├── package.json
│   ├── wrangler.toml
├── src                              <-- page source
│   ├── ...
├── .gitignore
├── package.json
├── yarn.lock
```

The workflow configuration is just taken from GitHub examples:
```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install the npm modules
        run: yarn install --frozen-lockfile

      - name: Build the modules
        run: yarn build:dev

      - name: Run unit-tests
        run: yarn test:ci

      - name: Deploy to GCP Storage
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: tuup-servers
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: -m cp -r ./build/* gs://some.server.url/web-app-dev/

      - name: Publish Cloudflare Worker
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'serve-index-worker'
```
 Everything works fine, including the worker publishing, but caching post action fails:
```
Post actions/cache@v1
0s
##[error]The template is not valid. Access to the path '/home/runner/work/repository/.wrangler' is denied.,Permission denied
``` 
When checking the content of the workspace it shows that the `.wrangler` folder is creates with `root:root` ownership 
```
drwxrwx---    3 root   root     4096 Jan  7 12:09 .wrangler
```
while everything else is under `runner:docker`. 

I could not find any configuration parameter that would control how the wrangler action is executed. What am I missing? 🤔

**Comment by vpavlushkov** [comment]
Caching issue might be the one reported as https://github.com/actions/cache/issues/133, but I am still not clear why wrangler is ran as a root...

**Comment by dmitryyankowski** [comment]
Getting the same thing :( Bump! @signalnerve

**Comment by signalnerve** [comment]
hey all! thanks, i meant to check in on this issue. going to block off some time on monday to explore this, the issue of root/non-root come up in #12 as well, so will need to figure out what the right approach is. bear with me!

**Comment by dmitryyankowski** [comment]
Thank you @signalnerve!!!

**Comment by tillkruss** [comment]
@signalnerve: Any progress on this? The deploy step takes about 50s. It would be great to reduce this a bit, at least by merging #20.

**Comment by signalnerve** [comment]
finally getting a chance to look at this!

it seems like this may be fixable by `chmod`-ing the `~/.wrangler` folder, similar to what's done in this issue:

https://github.com/actions/cache/issues/133#issuecomment-598861309

i'm super motivated to land caching in this repo, so i appreciate the really detailed bug report. messing around with this over the next few days!

**Comment by motss** [comment]
I actually have a different error.

```
Error: .github/workflows/preview.yml (Line: 6[2](https://github.com/motss/test/runs/123?check_suite_focus=true#step:15:2), Col: 16):
Error: The template is not valid. .github/workflows/preview.yml (Line: 62, Col: 16): hashFiles('**/package-lock.json') failed. Fail to hash files under directory '/home/runner/work/test/test'
```

```yaml
name: preview

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'

defaults:
  run:
    shell: bash

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  NODE_VERSION: v0.0.0
  NPM_CACHE_DIR: ~/.npm
  NPM_VERSION: 0.0.0

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List versions
        run: |
          pwd
          ls -la
          npm version
          which npm
          echo "NODE_VERSION=$(node -v)" >> $GITHUB_ENV
          echo "NPM_CACHE_DIR=$(npm config get cache)" >> $GITHUB_ENV
          echo "NPM_VERSION=$(npm -v)" >> $GITHUB_ENV

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v2
        with:
          # See this glob workaround at https://github.com/actions/toolkit/issues/713.
          path: |
            ${{ env.NPM_CACHE_DIR }}/*
            !${{ env.NPM_CACHE_DIR }}/_npx
          key: ${{ matrix.os }}-node-${{ env.NODE_VERSION }}-npm-${{ env.NPM_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ env.NODE_VERSION }}-npm-${{ env.NPM_VERSION }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '1.19.8'
```
