### ISSUE TITLE
Action fails on first deployment if secrets are used

### ISSUE THREAD

**Issue by 1000hz** [cloudflare/wrangler-action#162]
We currently upload secrets before deploying the script, but this understandably will fail if the script has never been deployed yet. We should think about how to prevent this, e.g. "touch" the script if we get a 404 response and retry.

**Comment by penalosa** [comment]
Wrangler _should_ do this by default (it uploads an empty script). Is this failing somehow?

**Comment by 1000hz** [comment]
Yeah, I was observing API errors. Perhaps that fallback behavior wasn’t implemented for `wrangler secret:bulk`.

**Comment by madhusudhand** [comment]
I ran into the same issue. Without a secret, workers script gets deployed successfully.

<img width="1145" alt="image" src="https://github.com/cloudflare/wrangler-action/assets/1935113/3675a320-d146-4be9-b370-22b3862651d5">

I believe I have the right configuration.

```
- name: Deploy
  uses: cloudflare/wrangler-action@v3
  with:
    accountId: ${{ secrets.CF_ACCOUNT_ID }}
    apiToken: ${{ secrets.CF_API_TOKEN }}
    workingDirectory: my-app
    command: deploy --env dev
    secrets: DB_SECRET
  env:
    DB_SECRET: ${{ secrets.DB_SECRET }}
```

I expected some detailed error message, so that I know what's wrong. Looks like in the exception catch block the error message is not printed.

**Comment by theetherGit** [comment]
I think we can use vars also. Some basic variable are not needed to be secrets.

```js
- name: Deploy
  uses: cloudflare/wrangler-action@v3
  with:
    accountId: ${{ secrets.CF_ACCOUNT_ID }}
    apiToken: ${{ secrets.CF_API_TOKEN }}
    workingDirectory: my-app
    command: deploy --env dev
    vars: DB_SECRET
  env:
    DB_SECRET: ${{ secrets.DB_SECRET }}
```
Worked for me as of now

**Comment by hubertott** [comment]
> I ran into the same issue. Without a secret, workers script gets deployed successfully.
> 
> <img alt="image" width="1145" src="https://user-images.githubusercontent.com/1935113/264743442-3675a320-d146-4be9-b370-22b3862651d5.png">
> I believe I have the right configuration.
> 
> ```
> - name: Deploy
>   uses: cloudflare/wrangler-action@v3
>   with:
>     accountId: ${{ secrets.CF_ACCOUNT_ID }}
>     apiToken: ${{ secrets.CF_API_TOKEN }}
>     workingDirectory: my-app
>     command: deploy --env dev
>     secrets: DB_SECRET
>   env:
>     DB_SECRET: ${{ secrets.DB_SECRET }}
> ```
> 
> I expected some detailed error message, so that I know what's wrong. Looks like in the exception catch block the error message is not printed.

I'd agree this is also a chicken and egg problem.

However, I also think the issue is the fact that we are now being asked to pass the `--env` to the command. eg. `deploy --env dev` But as mentioned the secret is uploaded prior to that. At that point Wrangler does not know what environment you are in.

As per the ambiguous warning which states:
> Since you have specified an environment you need to make sure to pass in '--env dev' to your command.

You need to be including the environment parameter to the action as well as the command 
`environment: dev`
ie.
 ```
 - name: Deploy
   uses: cloudflare/wrangler-action@v3
   with:
     accountId: ${{ secrets.CF_ACCOUNT_ID }}
     apiToken: ${{ secrets.CF_API_TOKEN }}
     environment: dev
     workingDirectory: my-app
     command: deploy --env dev
     secrets: DB_SECRET
   env:
     DB_SECRET: ${{ secrets.DB_SECRET }}
 ```

**Comment by timothymiller** [comment]
Experiencing this issue too

**Comment by 1000hz** [comment]
FWIW we'll still need a PR to bump the default version of wrangler

**Comment by aroman** [comment]
@JacobMGEvans i don't think your PR quite fixes this.

1) while your PR does create a draft worker, it [preserves the `return false`](https://github.com/cloudflare/workers-sdk/pull/4028/files#diff-27f9b554e27dcc6cfa0866e3f13671a9ccdfae4815456fb80340b4737930b53aR422), so the wrangler command will fail even though the secrets upload successfully. furthermore, the log "succesfully created secret for key" is suppressed in the draft-worker codepath ([source](https://github.com/cloudflare/workers-sdk/pull/4028/files#diff-27f9b554e27dcc6cfa0866e3f13671a9ccdfae4815456fb80340b4737930b53aR403))

2) as a result, while the PR _does_ cause create a draft worker to be created and the secrets succesfully uploaded, the wrangler command exits uncleanly (code `1`), and logs:

```
✨ 0 secrets successfully uploaded

✘ [ERROR] 🚨 7 secrets failed to upload
```

3) also, somewhat concerning but perhaps not a big problem, the draft worker creation occurs within a `Promise.all()` call, so it might happen multiple times as part of the promise race. since there is no real "bulk secret" upload (just a faked version with a bunch of concurrent promises to upload individual secrets), an API call to create a draft worker is created _for each secret in the bulk secret list_

**Comment by vladinator1000** [comment]
I just migrated to wrangler-action v3 and this started happening to me. It fails indefinitely though, doesn't pass on retry.

Here's my workflow file
```
name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    env:
      ENVIRONMENT: production
      APP_SECRET: ${{ secrets.APP_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_IMAGES_API_TOKEN: ${{ secrets.CLOUDFLARE_IMAGES_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: c-hive/gha-yarn-cache@v2

      - name: Get version
        id: version
        run: echo "::set-output name=version::$(date +'%Y-%m-%dT%H:%M:%S')-${{ github.sha }}"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: 🔨📦 Build and deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: 'production'
          secrets: |
            APP_SECRET
            DATABASE_URL
        env:
          VERSION: ${{steps.version.outputs.version}}
          STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
          STRIPE_WEBHOOK_SECRET: ${{secrets.STRIPE_WEBHOOK_SECRET}}
          STRIPE_CONNECT_WEBHOOK_SECRET: ${{secrets.STRIPE_CONNECT_WEBHOOK_SECRET}}
```
