### ISSUE TITLE
Error after successful deployment `fatal: bad object <SHA>`

### ISSUE THREAD

**Issue by zanieb** [cloudflare/wrangler-action#169]
Hi!

I'm getting a confusing error after a successful deployment when using this action:

```
Run cloudflare/wrangler-action@v3.1.1
📥 Installing Wrangler
  Running command: npm install wrangler@3.5.1
  npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
  npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
  ✅ Wrangler installed
🚀 Running Wrangler Commands
  🚀 Executing command: npx wrangler pages deploy site --project-name=ruff-docs --branch main --commit-hash ${GITHUB_SHA}
  Uploading... (728/730)
  Uploading... (729/730)
  Uploading... (730/730)
  ✨ Success! Uploaded 2 files (728 already uploaded) (1.39 sec)
  
  ✨ Deployment complete! Take a peek over at https://02459792.ruff-docs.pages.dev/
  
  Error: fatal: bad object 0181c74ed05496287668a263116ceef6a93f582a
  ▲ [WARNING] Warning: Your working directory is a git repo and has uncommitted changes
  
    To silence this warning, pass in --commit-dirty=true
```
[Full logs](https://github.com/astral-sh/ruff/actions/runs/6161239564/job/16720027659)

Our invocation looks like this 

```yaml
        uses: cloudflare/wrangler-action@v3.1.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # `github.head_ref` is only set during pull requests and for manual runs or tags we use `main` to deploy to production
          command: pages deploy site --project-name=ruff-docs --branch ${{ github.head_ref || 'main' }} --commit-hash ${GITHUB_SHA}
```
[Source](https://github.com/astral-sh/ruff/blob/0181c74ed05496287668a263116ceef6a93f582a/.github/workflows/docs.yaml#L48-L55)

This looks like a `git` error. The SHA `0181c74ed05496287668a263116ceef6a93f582a` does exist in the repository but might not be available due to a shallow checkout of the tag being deployed. I'm confused why any `git` commands are running though.
