### ISSUE TITLE
Error: Package manager is not detected

### ISSUE THREAD

**Issue by vipulgupta2048** [cloudflare/wrangler-action#180]
With the latest wrangler-action version, we were getting the following error due to the latest changes. 

```
file:///home/runner/work/_actions/cloudflare/wrangler-action/5a6b8d26847f6ab196fd2441fc52dc87b72c1b99/dist/index.mjs:2923
    throw new Error("Package manager is not detected");
          ^

Error: Package manager is not detected
    at realPackageManager (file:///home/runner/work/_actions/cloudflare/wrangler-action/5a6b8d26847f6ab196fd2441fc52dc87b72c1b99/dist/index.mjs:2923:11)
    at file:///home/runner/work/_actions/cloudflare/wrangler-action/5a6b8d26847f6ab196fd2441fc52dc87b72c1b99/dist/index.mjs:2925:48
```

Adding `packageManager: npm` to the actions YML file, in our case, resolved the issue after some digging around from the recent commits. Maybe create this as optional since this wasn't needed before? Or detecting it?

**Comment by aidxnharris** [comment]
What does your .yml file look like? I'm not very familiar with Github Action syntax.

**Comment by vipulgupta2048** [comment]
Here's an example: 

```
- name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.1.0 
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: '3.5.1' # latest - https://www.npmjs.com/package/wrangler
          preCommands: wrangler --version
          command: pages publish --branch $CF_BRANCH --project-name=$cloudflare_website  build/ | tee -a $GITHUB_STEP_SUMMARY
          packageManager: npm      # This is what you add

```
