### ISSUE TITLE
Error Installing Wrangler with pnpm

### ISSUE THREAD

**Issue by saviski** [cloudflare/wrangler-action#181]
This error started happening with the lates version

```
📥 Installing Wrangler
  Running command: pnpm add wrangler@3.5.1
  Error: Command failed: pnpm add wrangler@3.5.1
  Error: 🚨 Action failed
```

**Comment by 1000hz** [comment]
It seems like this could be a result of `pnpm` not being available in the runner environment. Are you including https://github.com/pnpm/action-setup in an earlier step of your workflow before `wrangler-action`?

**Comment by AdiRishi** [comment]
I just ran into this myself. For me I think the special case was that I'm using the `workingDirectory` property

```yml
- name: Deploy apex-gateway
  uses: cloudflare/wrangler-action@v3
  with:
    accountId: ${{ secrets.CF_ACCOUNT_ID || secrets.CLOUDFLARE_ACCOUNT_ID }}
    apiToken: ${{ secrets.CF_API_TOKEN || secrets.CLOUDFLARE_API_TOKEN }}
    workingDirectory: 'workers/apex-gateway'
    command: 'deploy'
```

My suspicion is that it is looking for `pnpm-lock.yaml` which doesn't exist when running in the subdirectory.

**Comment by AdiRishi** [comment]
Actually I'm now 100% sure that it's a bug because it's searching in the workingDirectory. We can see this in the codebase
```ts
function detectPackageManager(
	workingDirectory = ".",
): PackageManagerValue | null {
	if (existsSync(path.join(workingDirectory, "package-lock.json"))) {
		return "npm";
	}
	if (existsSync(path.join(workingDirectory, "yarn.lock"))) {
		return "yarn";
	}
	if (existsSync(path.join(workingDirectory, "pnpm-lock.yaml"))) {
		return "pnpm";
	}
	if (existsSync(path.join(workingDirectory, "bun.lockb"))) {
		return "bun";
	}
	return null;
}
```

This is likely a seperate issue to the one being reported, should I create a new issue report?

**Comment by 1000hz** [comment]
@AdiRishi yes, please open a new issue for that

**Comment by AdiRishi** [comment]
> @AdiRishi yes, please open a new issue for that

Done - https://github.com/cloudflare/wrangler-action/issues/198

**Comment by thantos** [comment]
> It seems like this could be a result of `pnpm` not being available in the runner environment. Are you including https://github.com/pnpm/action-setup in an earlier step of your workflow before `wrangler-action`?

Ran into the same error and I am 100% installing pnpm

```yml
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - name: do a bunch of things with pnpm

     - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./packages/portal/out --project-name=${{ vars.CF_PROJECT_NAME }}
```

**Comment by thantos** [comment]
Here is the actual error (from running locally since you swallow the error :( )

> ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.

Going to try with a working directory.

By the way, I already have it installed at the root, would be great if the action didn't need to do it again...

**Comment by thantos** [comment]
Which of course runs into this: https://github.com/cloudflare/wrangler-action/issues/198

This action doesn't work with pnpm workspaces.

**Comment by thantos** [comment]
Update: I was able to get by this with a hack

`wranglerVersion: "* -w"`

This uses the existing version of wrangler in the root pnpm and injects the `-w` needed to bypass the PNPM workspace root error.

**Comment by enfipy** [comment]
I was able to work around this issue with a pretty simple change, just by setting `packageManager: pnpm` near the `workingDirectory` property:
```yaml
- uses: cloudflare/wrangler-action@v3
  with:
    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    workingDirectory: ./<PATH_TO_PACKAGE>/
    environment: production
    packageManager: pnpm
```

The issue indeed is because of [getPackageManager](https://github.com/cloudflare/wrangler-action/blob/533097350a4f5b9731d84ec31b08d1197e9c87f8/src/index.ts#L35) function tries to retrieve `packageManager` from [detectPackageManager(workingDirectory)](https://github.com/cloudflare/wrangler-action/blob/533097350a4f5b9731d84ec31b08d1197e9c87f8/src/packageManagers.ts#L66), and when `workingDirectory` is a subdirectory of workspace (e.g. without `pnpm-lock.yaml`) - it results in an error. So explicitly setting `packageManager: pnpm` - solves this issue.

I think we can close this issue in regard to #198.

**Comment by 1000hz** [comment]
@thantos thanks for investigating. It looks like there are two distinct problems here:

* The missing `-w` flag in the install command causes pnpm to error
* Package manager inference fails when workspaces are used (#198)

I'll keep this issue open to track the first problem.
Installation error stdout being swallowed should be addressed by #171.
I'll also open a new issue to track installing wrangler only when it's not already installed.

**Comment by maxpetretta** [comment]
Added my solution here: https://github.com/cloudflare/wrangler-action/issues/198#issuecomment-1771357679

**Comment by sam-goodwin** [comment]
> Update: I was able to get by this with a hack
> 
> `wranglerVersion: "* -w"`
> 
> This uses the existing version of wrangler in the root pnpm and injects the `-w` needed to bypass the PNPM workspace root error.

This workaround isn't working for me.

I have opened a PR with an attempt to fix this: https://github.com/cloudflare/wrangler-action/pull/207

**Comment by skf-funzt** [comment]
> Update: I was able to get by this with a hack
> 
> `wranglerVersion: "* -w"`
> 
> This uses the existing version of wrangler in the root pnpm and injects the `-w` needed to bypass the PNPM workspace root error.

Unfortunately, this solution lets the action fail with
```
🚀 Running Wrangler Commands
Error: Invalid Version: * -w
Error: 🚨 Action failed
```

**Comment by Ambroos** [comment]
Since v3.6.0, released a few hours ago, the action will reuse an existing Wrangler installation.
You can just pre-install your favourite wrangler version and this is no longer an issue: https://github.com/cloudflare/wrangler-action/releases/tag/v3.6.0

**Comment by IanVS** [comment]
Is anyone else here having this issue when setting `packageManager: pnpm` and also setting `workingDirectory`? https://github.com/cloudflare/workers-sdk/issues/6224

**Comment by broisnischal** [comment]
I am still having problem doing, but and what if I am using bun as the package manager?

**Comment by stevefrench39** [comment]
Would `--ignore-workspaces` break other functionality?
https://github.com/orgs/pnpm/discussions/4735#discussioncomment-2770033

**Comment by VoloshchenkoAl** [comment]
Workaround that works for me:
1. Install the `wrangler` to the root `package.json` of your workspace
2. Skip `wranglerVersion` in `cloudflare/wrangler-action@v3`:
```yml
    - name: Publish project to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.cloudflare-api-token }}
        accountId: ${{ inputs.cloudflare-account-id }}
        gitHubToken: ${{ inputs.github-token }}
        command: pages deploy ${{ inputs.assets-directory }} --project-name=${{ inputs.project }} --branch=${{ inputs.branch }}
```
3. The `cloudflare/wrangler-action@v3` will get an installed version of the `wrangler` from the `package.json`
<img width="646" alt="Image" src="https://github.com/user-attachments/assets/7f291fa0-3548-460e-80c1-0d0f82718ac4" />
