### ISSUE TITLE
feature request: secrets publishing

### ISSUE THREAD

**Issue by Cherry** [cloudflare/wrangler-action#19]
We maintain secrets in GitHub Actions for different environments, and now with the [new secrets release](https://blog.cloudflare.com/workers-secrets-environment/) available in Workers, it would be fantastic to be able to publish secrets directly using this action.

Something like:

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          secrets:
            - foo: ${{ secrets.production_foo }}
            - bar: ${{ secrets.production_bar }}
```

This would allow us to set and deploy secrets in GitHub actions for different environments, without having someone manually issue `wrangler secret` commands, or manually creating our own step where we `npm install` wrangler, and run the commands inline.
