### ISSUE TITLE
Wrangler is reinstalled even when it's already available

### ISSUE THREAD

**Issue by 1000hz** [cloudflare/wrangler-action#199]
Currently, `wrangler-action` always installs wrangler as specified by the `wranglerVersion` input or the `DEFAULT_WRANGLER_VERSION` constant contained in the source. This isn't always necessary as Wrangler may have already been installed in a previous step of the workflow (e.g. if it's declared in the project's dependencies in `package.json`). This also makes it harder to keep the version of Wrangler used by `wrangler-action` and the version used locally consistent, as the user needs to manually keep `wranglerVersion` and `package.json` in sync.

Instead, we should only install Wrangler if it's not already present in the `$PATH` (including the package manager bin directory) OR if `wranglerVersion` has been explicitly provided

**Comment by peplin** [comment]
+1 but also wanted to mention that not having the option to disabling this install is preventing my team from using this action because of the hugely increased runtime. The action runs `yarn add wrangler` and triggers linking for our entire (large) list of dependencies, and this action takes > 2 minutes. `npx wrangler` is ready in < 3 seconds, for comparison.

**Comment by AdiRishi** [comment]
I've recently moved all my projects to use `wrangler-action` in CI. Definitely hit this quite a few times now.
I've made a PR with a fix 🙏

**Comment by TonyRL** [comment]
@petebacondarwin Please reopen this issue due to #265.

**Comment by wqcstrong** [comment]
> I've recently moved all my projects to use `wrangler-action` in CI. Definitely hit this quite a few times now. I've made a PR with a fix 👍

@AdiRishi Thanks for your contribution. However, I am currently facing some issues with my project setup. My project uses yarn workspaces. Even though I have executed `yarn install` which installs wrangler@3.61.0 at the workspace root in `bash ./build.sh` , it seems that the check here https://github.com/cloudflare/wrangler-action/blob/main/src/index.ts#L117-L124 did not pass. 

```json
// "package.json" in workspace root 
{
  "name": "sony-pages",
  "workspaces": [
    "apps/*"
  ],
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "deploy": "wrangler deploy",
    "dev": "wrangler dev",
    "start": "wrangler dev",
    "test": "vitest"
  },
  "devDependencies": {
    "@cloudflare/kv-asset-handler": "^0.3.3",
    "@cloudflare/workers-types": "^4.20240620.0",
    "lerna": "^8.1.5",
    "typescript": "^5.0.4",
    "vitest": "1.3.0",
    "wrangler": "^3.61.0"
  },
  "dependencies": {}
}
```

```yaml
// the workflow yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          bash ./build.sh

      - name: Deploy to cloudflare
        uses: cloudflare/wrangler-action@v3.6.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Lark bot notify
        run: |
          curl -X POST \
              -H "Content-Type: application/json" \
              ...
```

Do you know what could be the reason for this? Below is a screenshot of the results from my workflow execution.

![image](https://github.com/cloudflare/wrangler-action/assets/23474513/89b8b305-8566-4a6d-bac1-e69bab1f967d)
