### ISSUE TITLE
Commands piped to Wrangler doesn't work in GitHub Actions

### ISSUE THREAD

**Issue by vipulgupta2048** [cloudflare/wrangler-action#210]
Here's our GitHub action step using Wrangler Action.

```
    - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@5e8484995321734668f14981c316aa9188d76ed1 # v3.3.2
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: "3.5.1" 
          preCommands: wrangler --version
          postCommands: wrangler pages deploy --branch ${{ env.CF_BRANCH }} --project-name=${{ inputs.cloudflare_website }} build/ | tee -a $GITHUB_STEP_SUMMARY
```

This command used to work, but is now failing when trying out the new wrangler-action v3.3.2 with the following error. We used the pipe to get command output into GitHub Step Summary for a nice bit of result and get the Cloudflare pages draft URL.  

Here's the error: The wrangle command tries to check what these arguments are as well. 
```
🚀 Running Wrangler Commands
  /home/runner/_work/_tool/node/18.18.2/x64/bin/npx wrangler pages deploy --branch renovate/cloudflare-wrangler-action-3.3.x --project-name=flowzone build/ | tee -a $GITHUB_STEP_SUMMARY`


  ✘ [ERROR] Unknown arguments: a, |, tee
```

I recommend that we define proper outputs for this action in the `action.yml` file. These standardized outputs can be used by folks anywhere? Can add that myself if people agree?

Link of the action run: https://github.com/product-os/flowzone/actions/runs/6905675937/job/18789164936
