### ISSUE TITLE
Error: Unable to Locate Executable File: bun in wrangler-action@v3

### ISSUE THREAD

**Issue by bkyerv** [cloudflare/wrangler-action#222]
Environment:
GitHub Actions Runner: [ubuntu-latest]
Wrangler Action Version: cloudflare/wrangler-action@v3

Issue Description:
When using cloudflare/wrangler-action@v3 in our GitHub Actions workflow, the action fails with the following error:

📥 Installing Wrangler

- Error: Unable to locate executable file: bun. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
- Error: 🚨 Action failed

Steps to Reproduce:
- Set up a GitHub Actions workflow using cloudflare/wrangler-action@v3.
- Run the workflow.
- Observe the error during the "Installing Wrangler" step.

Expected Behavior:

- The action should successfully install and run Wrangler without requiring additional steps to install or configure bun.

Actual Behavior:
The action fails with an error indicating that bun cannot be located or is not executable.

1. Is bun a new requirement for wrangler-action@v3, and if so, what is the recommended way to set it up in a GitHub Actions environment?
2. Are there alternative configurations or versions of the action we should use that do not require bun?

**Comment by pippinmole** [comment]
Why did you close this? Did you fix it? This is still an issue.

**Comment by oasisMystre** [comment]
Why is this closed?

**Comment by leonex16** [comment]
If this helps anyone: in my case, I run the build in a separate job. When the deploy job runs, `wrangler-action` automatically detects that the project uses Bun, but at that point it’s no longer necessary

Since the build artifacts are already generated, I can explicitly set `packageManager: npm` in the deploy step to avoid these error

```yaml
jobs:
  build:
    # ... build steps

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: cloudflare_deploy
        with:
          packageManager: npm # Explicitly set to avoid Bun requirement
```
