### ISSUE TITLE
Passing environment variables

### ISSUE THREAD

**Issue by tillkruss** [cloudflare/wrangler-action#24]
We'd love to pass environment variables to the Worker Site similar to how secrets work:

```js
addEventListener('fetch', event => {
  console.log(process.env.RELEASE) // coming from `jobs.*.steps.step.with`
  console.log(STRIPE_SECRET) // coming from `wrangler secret put STRIPE_SECRET`
})
```

A use case for this would be Sentry Releases. We want to report errors happening in Workers Sites to Sentry. It would be really useful to also pass the GitHub SHA as the "RELEASE" constant.

```yml
steps:
      - uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          RELEASE: ${GITHUB_SHA} # or: ${github.sha}
```

@signalnerve: Any thoughts on this? Is this already possible somehow?
