### ISSUE TITLE
Cannot get CLOUDFLARE_API_TOKEN in Actions

### ISSUE THREAD

**Issue by wavy-cat** [cloudflare/wrangler-action#246]
Authorization error on v3.4.1:
```
  ✘ [ERROR] In a non-interactive environment, it's necessary to set a CLOUDFLARE_API_TOKEN environment variable for wrangler to work. Please go to https://developers.cloudflare.com/fundamentals/api/get-started/create-token/ for instructions on how to create an api token, and assign its value to CLOUDFLARE_API_TOKEN.
```

Workflow:
```yaml
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./generate/web --project-name=assets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
```

**Comment by aialok** [comment]
I am also getting the same error.
https://github.com/json-schema-org/landscape/actions/runs/8840354725/job/24275518908#step:8:25

**Comment by aialok** [comment]
@wavy-cat  If you are running this on pull request from forked branch then this will through error as deployment and secrets are only valid in main repo. 

https://github.com/actions/runner/discussions/3039
https://stackoverflow.com/questions/73866908/github-actions-main-repository-secret-not-picked-up-from-pull-request-build

**Comment by wavy-cat** [comment]
The issue was that the token had been added to the Environment secrets instead of the Repository secrets. Due to this oversight, the deployment did not function as intended. It was a mistake on my part, I'm sorry.

**Comment by citypaul** [comment]
> The issue was that the token had been added to the Environment secrets instead of the Repository secrets. Due to this oversight, the deployment did not function as intended. It was a mistake on my part, I'm sorry.

Thanks for writing this here as I just made the exact same mistake! Doh!!

**Comment by Ruben-Smit** [comment]
I had this same issue. For me the solution was to get rid of any `accountId` properties in the pipeline (it was truncating the last 2 characters of my accountId in the wrangler-action for some reason) and only add it in the wrangler.toml: `account_id = "XXXXX"`. I hope this helps anyone else.

By the way, on a newer wrangler version the error turns into this:
```  
Could not route to /client/v4/accounts/XXXXX/workers/services/XXXXX, perhaps your object
  identifier is invalid? [code: 7003]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```
The solution is still the same; add account_id in the wrangler.toml.

EDIT:
It happened again; this time the solution was to add the CLOUDFLARE_API_TOKEN to the **dependabot** secrets in the repository settings. (In my project dependabot can also trigger deployments, but this didn't use the same secrets as a deployment triggered by me.)

**Comment by mragochar** [comment]
In my case, I was using reusable workflow and was accessing secrets without passing them. The fix is to define `secrets:` block on the reusable workflow and pass from the caller side.
Caller:
```yaml
jobs:
  deploy-preview:
    uses: ./.github/workflows/deploy-pages.yaml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
```
Reusable Workflow:
```yaml
on:
  workflow_call:

    secrets:
      CLOUDFLARE_API_TOKEN:
        description: 'Cloudflare API token used by wrangler to authenticate'
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        description: 'Cloudflare account ID the Pages project belongs to'
        required: true
```
Happy deploying! You can see this in [github how-tos](https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows#using-inputs-and-secrets-in-a-reusable-workflow)
