### ISSUE TITLE
D1 migrations won’t apply due to unexpected field in `wrangler.toml`

### ISSUE THREAD

**Issue by MrSuttonmann** [cloudflare/wrangler-action#250]
I am attempting to deploy an Angular application which uses Functions and a D1 database.

As such, I’d like to perform database migrations as part of the deployment CI/CD pipeline.

I’ve done this at the moment as a `preCommands` on the wrangler action, which looks like so:

```
- uses: cloudflare/wrangler-action@v3.1.0
          name: Deploy
          with:
            # Your Cloudflare API Token
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            # Your Cloudflare Account ID
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            preCommands: |
              npm run build
              export NO_D1_WARNING=true && npx wrangler d1 migrations apply prod-octo-db
            command: pages deploy dist/cloudflare --project-name=octo-analytix-app
```

This fails in the pipeline with the following error:

```
Error: ▲ [WARNING] Processing wrangler.toml configuration:
  
      - Unexpected fields found in top-level field: "pages_build_output_dir"
  ```

Obviously I can’t remove the field as it’s required for the Pages deployment, so I’m a little stuck now unless anyone has any suggestions?
