### ISSUE TITLE
How can you set worker secret for a specific environment?

### ISSUE THREAD

**Issue by tien** [cloudflare/wrangler-action#251]
```yaml
- uses: cloudflare/wrangler-action@v3
  with:
    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    command: deploy --env production
    secrets: |
      SUPER_SECRET
  env:
    SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
```

Assuming the worker name is `my-worker` doing the above would create 2 workers: `my-worker` & `my-worker-production` with the secrets only set for `my-worker`.
