### ISSUE TITLE
 [ERROR] Must specify a project name.

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [cloudflare/wrangler-action#254]
Dear all,

Running the action on my CI/CD results in the following error

```bash
Installing Wrangler
  /home/runner/.bun/bin/bun i wrangler@3.13.2
  bun add v1.1.4 (fbe2fe0c)
   Saved lockfile
   installed wrangler@3.[13](https://github.com/FrancescoSaverioZuppichini/nextjs-cloudfare/actions/runs/8822788384/job/24221760187#step:8:14).2 with binaries:
    - wrangler
    - wrangler2
  [[14](https://github.com/FrancescoSaverioZuppichini/nextjs-cloudfare/actions/runs/8822788384/job/24221760187#step:8:15).00ms] done
  ✅ Wrangler installed
🚀 Running Wrangler Commands
  /home/runner/.bun/bin/bunx wrangler pages deploy .vercel/output/static --env preview
  ✘ [ERROR] Must specify a project name.
  ```
  
  The `yml` file is:
  
  ```yml
        - name: Deploy
        uses: cloudflare/wrangler-action@v3.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy .vercel/output/static --env preview
          packageManager: bun
 ```
 
 While, when I run the command locally
 
 ```bash
 wrangler pages deploy .vercel/output/static --env preview
```

Everything is fine

```bash
✨ Compiled Worker successfully
✨ Uploading Worker bundle
✨ Uploading _routes.json
✨ Deployment complete! Take a peek over at bla bla bla
```

Thanks a lot ❤️ 

Cheers,

Fra
