### ISSUE TITLE
Is it possible to skip wrangler install?

### ISSUE THREAD

**Issue by zoubingwu** [cloudflare/wrangler-action#259]
Looks like there is no way to skip the wrangler installations.

I already have it in package.json and all dependencies will be installed before deploy:

```json
{
    "devDependencies": {
		"wrangler": "3.53.0"
	}
}
```

```yml
- uses: actions/checkout@v4
- uses: pnpm/action-setup@v3
  with:
    version: 8
- uses: actions/setup-node@v4
  with:
    node-version: 'lts/Iron'
    cache: 'pnpm'
- name: Install dependencies
  run: pnpm install
- name: Deploy
  uses: cloudflare/wrangler-action@v3
  with:
      apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
```

But it installed another old version

<img width="689" alt="image" src="https://github.com/cloudflare/wrangler-action/assets/18644268/e01aca77-f9c6-4276-9584-84043fa1ea29">

Is there any way to skip it from installing twice?
