### ISSUE TITLE
Dependencies cannot be installed in version 3.6.0

### ISSUE THREAD

**Issue by tomaco-gojiraf** [cloudflare/wrangler-action#264]
I was deploying normally and suddenly my pipeline started to fail, and it just happened to coincide with the release of the new action version (3.6.0).
It fails when trying to install the package.json dependencies throwing an error that it cannot resolve the dependency. The error is thrown on the import line of the code and advises you to mark it as external to fix it, but this sounded strange to me because it was already working this way.

> ✘ [ERROR] Could not resolve "@tsndr/cloudflare-worker-jwt"
> 
>    src/auth/validate-token.ts:1:23:
>       1 │ import { verify } from '@tsndr/cloudflare-worker-jwt';
>         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>   You can mark the path "@tsndr/cloudflare-worker-jwt" as external to exclude it from the bundle, which will remove this error.

The same error happens with zod dependency:
> Could not resolve "zod"

**Using the action version 3.5.0 fixed the problem quickly.**

I also tried using bun as a package manager thinking it might be a npm problem, but it didn't fix anything.

GitHub Action:

```yaml
name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: cloudflare/wrangler-action
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: 3.57.1
          secrets: |
            SECRET_KEY
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
```

**Comment by edgeboy47** [comment]
+1

**Comment by Maximo-Guk** [comment]
Hey @tomaco-gojiraf and @edgeboy47  👋!

I can't reproduce dependency installation issues using the new action version `3.6.0` on my [repository](https://github.com/Maximo-Guk/demo-actions/actions/runs/9214136903/job/25349657301). 

From the logs you linked it looks to me like it may be a package installation issue, I would double check that `zod` and `@tsndr/cloudflare-worker-jwt` are both in your `package.json` and that's you've ran `npm install`. 

Would it be possible for one you to provide me with a reproduction repository that has this issue?

Thank you! 🙏

**Comment by svrnhdl** [comment]
Same issue here. Had an old worker on wrangler version 3.23.0 that I updated to 3.57.1 with wrangler-action@v3. Weird thing was that Github Actions was still using 3.23.0 for a while and then suddenly stopped working when it installed 3.57.1.

downgrading to action version 3.5.0 fixed it.
![image](https://github.com/cloudflare/wrangler-action/assets/49792942/afbad1f0-fa00-4bd8-890c-6b33d1d845af)

**Comment by kchro3** [comment]
+1 that i'm seeing this issue too with multiple packages:

```

    ...: ERROR: Could not resolve "@tsndr/cloudflare-worker-jwt"
    ...: ERROR: Could not resolve "hono/streaming"
    ...: ERROR: Could not resolve "openai"
    ...: ERROR: Could not resolve "@anthropic-ai/sdk"
    ...: ERROR: Could not resolve "postgres"
```

**Comment by AdiRishi** [comment]
A reproduction repository would be very helpful 🙏 
I just upgraded three different repos I have to `3.6.0` and it's worked everywhere.

Also, some context on what `wrangler-action` was doing when it failed would be good. Here are some of the steps that run.
```
🔍 Checking for existing Wrangler installation
📥 Installing Wrangler (only run if installation is necessary)
🔑 Uploading secrets...
🚀 Running Wrangler Commands
```

Some questions
- Was it trying to install wrangler?
- If it was trying to install wrangler, is it using the correct package maanger?
- Do you expect it to install wrangler? The new change in 3.6.0 will use your local wrangler version if it's present.

**Comment by sakettawde** [comment]
Adding context since am facing a similar issue.

Absolutely nothing changed in my code. It started failing today.

Issue seen:
<img width="1349" alt="image" src="https://github.com/cloudflare/wrangler-action/assets/14161564/bdd36cf2-db22-4f76-b673-21793cd05505">

Changed my github workflow file by specifying to use v3.5 for wrangler-action as below:
<img width="340" alt="image" src="https://github.com/cloudflare/wrangler-action/assets/14161564/b7b0d6cd-921e-4147-925d-d7e5535fdb14">

And now it runs as before. Screengrab of logs below:
<img width="1348" alt="image" src="https://github.com/cloudflare/wrangler-action/assets/14161564/7c03beb6-2bdf-41b8-a08c-8e6bb73e8cd4">

**Comment by hiendaovinh** [comment]
I've the same issue. Pinning to v3.5.0 helps for now.

**Comment by AdiRishi** [comment]
Oh, I see what happened. Thanks for the screenshots @sakettawde .
In `3.6.0` we released a new feature which would check for an existing wrangler installation, and use it if appropriate.

The code which checks for an existing installation runs `npx wrangler --version` to determine if wrangler is installed. What I missed was that this command will automatically install the latest version of wrangler if no version is installed 🙃 

This means that by accident `wrangler-action` now always will install the latest wrangler if you don't specify `wranglerVersion` in the config. This is a breaking change and bug, since we meant for it to keep it's old behavior and install version `3.13.2` by default.

For everyone who's build is now failing, I suspect your codebase has something about it which requires that older version of wrangler, since your build fails when using version `3.57.1`. In order to restore previous behavior, simply pin `wranglerVersion` to `3.13.2` like this
```yml
jobs:
  deploy:
    steps:
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        wranglerVersion: "3.13.2"
```

I'll work on making a PR to fix this issue.
