### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by its-dibo** [cloudflare/wrangler-action#27]
I created a very simple worker, trying to deploy it to cloudflare workeres, but got an error without any details.
```
Error: No such file or directory (os error 2)
```

github action:
```
name: Build and Deploy to firebase, cloudflare-workers, ..
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Caching node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm 
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-152020
      - name: Install devDpendencies
        run: |
          sudo chown -R $USER /usr
          npm install --no-audit
          npm install -g @angular/cli
      - name: Build
        run: npm run build
      - name: Deploy to CloudFlare workers
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiKey: ${{ secrets.CLOUDFLARE_API_KEY }}
          email: ${{ secrets.CLOUDFLARE_EMAIL }}
        env:
          # https://github.com/cloudflare/wrangler-action/issues/12#issuecomment-588226602
          USER: root
```
wrangler.toml
```
name = "myworker"
type = "webpack"
account_id = "***"
route = "www.almogtama3.com/api/v1/cloudflare"
zone_id = "***"
webpack_config="./webpack.server.config.js"

[site]
entry-point="./dist/server/cloudflare-workers.js"
bucket="./dist/browser"
```

webpack.server.config.js
```
const webpackServer = require("./webpack.server.config.js");

module.exports = Object.assign(webpackServer, {
  target: "webworker",
  mode: "production",
  entry: {
    "cloudflare-workers": "./src/server/cloudflare-workers.js"
  }
});
```

webpack.server.config.js
```

const path = require("path");
const webpack = require("webpack");

module.exports = {
  target: "node",
  mode: "none",
  entry: {
    express: "./src/server/express.ts"
  },
  externals: {
    "./dist/server/main": 'require("./main")',
    sharp: "commonjs sharp" //https://github.com/lovell/sharp/issues/794#issuecomment-306555683
  },
  //https://github.com/googleapis/gax-nodejs/issues/719#issuecomment-605250814
  resolve: {
    extensions: [".ts", ".js", ".json"],
    alias: { pkg: path.resolve(__dirname, "./packages") }
  },
  optimization: {
    minimize: false
  },
  output: {
    // Puts the output at the root of the dist folder
    path: path.join(__dirname, "dist/server"), //todo: `dist/${this.mode}`
    filename: "[name].js", //'[name]' = entry[$key]
    library: "",
    libraryTarget: "commonjs-module"
    //fix: setting library & libraryTarget to fix issue: require('./server.js') == undefined
    //https://github.com/webpack/webpack/issues/2030#issuecomment-232886608
    //https://github.com/webpack/webpack/issues/2030#issuecomment-290363910
  },
  module: {
    noParse: /polyfills-.*\.js/,
    rules: [
      { test: /\.ts$/, loader: "ts-loader" },
      {
        // Mark files inside `@angular/core` as using SystemJS style dynamic imports.
        // Removing this will cause deprecation warnings to appear.
        test: /(\\|\/)@angular(\\|\/)core(\\|\/).+\.js$/,
        parser: { system: true }
      },
      {
        //load .node files
        //ex: ./node_modules/sharp/build/Release/sharp.node
        // https://github.com/lovell/sharp/issues/794#issuecomment-307188099
        test: /\.node$/,
        use: "node-loader"
      }
    ]
  },
  plugins: [
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      //https://webpack.js.org/plugins/context-replacement-plugin/
      /(.+)?angular(\\|\/)core(.+)?/,
      path.join(__dirname, "src"), // location of your src
      {} // a map of your routes
    ),
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?express(\\|\/)(.+)?/,
      path.join(__dirname, "src"),
      {}
    )
  ]
};

```

and here is the error in action
https://github.com/goblins-tech/almogtama3/runs/720247249?check_suite_focus=true#step:8:56
