### ISSUE TITLE
Deploy a simple python worker, invoke error：  No loader is configured for ".py" 

### ISSUE THREAD

**Issue by freelixilong** [cloudflare/wrangler-action#270]
![Screenshot from 2024-06-13 16-43-33](https://github.com/cloudflare/wrangler-action/assets/23396760/6e349606-bf86-4ce7-b5e3-f4ea87b6f97e)

**Comment by freelixilong** [comment]
May be my problem

**Comment by Hugo-C** [comment]
This seems linked to the wrangler version, adding it like:
```yaml
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "latest"  <-- HERE
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
```
fixed it for me.
Related to #238
