### ISSUE TITLE
Feature request: Support GitHub deployments

### ISSUE THREAD

**Issue by sebdanielsson** [cloudflare/wrangler-action#274]
I'm coming from the deprecated pages-action and one feature I really miss is being able to update the GitHub deployments environment.

**Comment by Hugo-C** [comment]
adding:
```yaml
    environment: <environment_name>
```
works for me [here](https://github.com/Hugo-C/threatfox-daily-c2/blob/dfca7d7b217c3cd0e2bc787b1e677829f1fe75f2/.github/workflows/deploy.yml), is it what you are looking for ?

**Comment by sebdanielsson** [comment]
> adding:
> 
> ```yaml
>     environment: <environment_name>
> ```
> 
> works for me [here](https://github.com/Hugo-C/threatfox-daily-c2/blob/dfca7d7b217c3cd0e2bc787b1e677829f1fe75f2/.github/workflows/deploy.yml), is it what you are looking for ?

My understanding is that this is for choosing which Cloudflare Pages environment to deploy to. Not the GitHub environment for deployments.

https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

**Comment by TheAifam5** [comment]
I have the same problem, the pages-action did set the proper url for preview/release deployments. With wrangler-actions I could for release  deployment I can hardcode it but how do I set the url when deploying preview?

**Comment by hellt** [comment]
I would love to have this as well.

And also the preview aliases are not set to the git branch for preview branches. It would be great to have them back =)

**Comment by hellt** [comment]
@nprogers ideally I'd love to have the same functionality as the CF-Pages+GitHub interfation provides via a bot leaving a comment with all the required information

<img width="668" alt="image" src="https://github.com/user-attachments/assets/d36fa581-aa59-450c-b94c-a58994a05401">

if this is not possible, then at least the gh api to be triggered to show the deployment environment with the preview URL as the current pages-action does:

<img width="875" alt="image" src="https://github.com/user-attachments/assets/5c494258-85dc-4cff-8c32-ec9159b30261">

**Comment by aaronadamsCA** [comment]
When you do implement this, please don't make users pass in the GitHub token manually (https://github.com/cloudflare/pages-action/issues/69). Actions can always access `github.token`, so this should really be a boolean flag for clarity.

Also please keep bot comments separate from deployments. I do _not_ want a bot leaving a comment on our PRs! I only want the deployments.

**Comment by dijitali** [comment]
I'm using the below as a workaround (basically grab the [`deployment-url` output](https://github.com/cloudflare/wrangler-action/blob/main/README.md#using-the-deployment-url-output-variable) from Wrangler and write it as a comment with the [GitHub Script Action](https://github.com/marketplace/actions/github-script)):

```yaml
on: [push]

...

      - name: Publish to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --commit-dirty=true
      - uses: actions/github-script@v7
        with:
          script: |
            const issue_number = (await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚢 deployed to <${{ steps.deploy.outputs.deployment-url }}>'
            })

```
