### ISSUE TITLE
Didn't deploy to production properly

### ISSUE THREAD

**Issue by srl295** [cloudflare/wrangler-action#287]
[this link](https://github.com/cloudflare/wrangler-action?tab=readme-ov-file#deploy-your-pages-site-production--preview) states:

> Deploy your Pages site (production & preview)
> If you want to deploy your Pages project with GitHub Actions rather than the built-in continous integration (CI), then this is a great way to do it. Wrangler 2 will populate the commit message and branch for you. You only need to pass the project name. If a push to a non-production branch is done, it will deploy as a preview deployment:

… 

```yaml
          command: pages deploy YOUR_DIST_FOLDER --project-name=example
```

But it didn't work for production.  It worked great for PR branches and generated a preview build, but when merging to main it did NOT update production.

My entire yaml is here:

```yaml
    - name: Deploy cldr.pages.dev
      id: deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy ./_site --project-name=cldr
```

am I missing something?  Otherwise I'll add a switch that adds `--env prod` or something as appropriate.
