### ISSUE TITLE
GH Actions Error

### ISSUE THREAD

**Issue by Skipperlla** [cloudflare/wrangler-action#336]
```
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
```

this is the actions code I use but I get this error when actions is running
<img width="711" alt="Screenshot 2024-12-01 at 21 52 45" src="https://github.com/user-attachments/assets/825c24e7-a0ed-4183-be1d-db600fedd7a4">
