### ISSUE TITLE
`pages deploy` does not deploy to production

### ISSUE THREAD

**Issue by dapperdandev** [cloudflare/wrangler-action#337]
I'm trying to deploy to `production` (not `preview`). There doesn't seem to be an option to do so.

```yaml
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy dist --project-name=app-${{env.ENV_NAME}}
```

![image](https://github.com/user-attachments/assets/a7db7c53-0347-45f1-afc5-0e886ea8030b)
