### ISSUE TITLE
v3.13.1 causes deployment failure

### ISSUE THREAD

**Issue by tenpaiyomi** [cloudflare/wrangler-action#347]
No changes introduced outside of the update from v3.13.0 to v3.13.1, however our CI process started throwing an error

```
Error: Resource not accessible by integration - https://docs.github.com/rest/deployments/deployments#create-a-deployment
Error: 🚨 Action failed
```

Applicable line in the Github Action

```
            - name: Deploy to Cloudflare Pages
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  command: pages deploy build/client --project-name ***** --branch ${{ env.GIT_BRANCH }}
                  workingDirectory: apps/web
```

Changing the version back to explicitly `v3.13.0` resolves the issue.
