### ISSUE TITLE
Set secret environment variables in Pages preview deployment

### ISSUE THREAD

**Issue by lorenzodejong** [cloudflare/wrangler-action#354]
Hi!

Currently I'm integrating a Cloudflare Pages application in combination with Worker functions which are connecting to a unique branch of my Postgres Database (using Neon).

However, what I noticed is that there's currently no functionality available to set environment variables (secrets) scoped to my unique preview deployment.

My setup for deploying from Github Actions is very similar to the following example: https://github.com/neondatabase/preview-branches-with-cloudflare/blob/main/.github/workflows/deploy-preview.yml#L42. What i noticed is that they explicitly set the `DATABASE_URL` in the `wrangler.toml`.

The downsides of this however:
- Cloudflare console does not mark these variables as sensitive/secret, but instead outputs them in the UI (especially concerning since it's database credentials).
- This works to some extent in the `wrangler.toml`, however when you start introducing [environments](https://developers.cloudflare.com/workers/wrangler/environments/) (e.g. `[env.dev]`) appending the variables at the end of the `wrangler.toml` may set the variables for the wrong environment.

Would like to hear if it's an oversight from my end and/or if there's any future plans on supporting this behavior. Thanks!

**Comment by schroeder-g** [comment]
I'd like to second the inquiry here. I'd benefit from a more granular API for secret management with pages. If I could e.g. `cloudflare secret put --preview`, that'd be spectacular. Alternatively, integration with the cloudflare secret store would be a splendid feature.

**Comment by ilyaryabchinski** [comment]
I noticed there is no way to set an env variable for pages deployments like
```
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          workingDirectory: apps/frontend
          command: pages deploy ./dist --branch=master --project-name=frontend
        env:
          API_URL: ${{ secrets.API_URL }}
```

so this API_URL part doesn't really work. Are there any workarounds/alternatives to that currently except the one suggested by @lorenzodejong ? I could not make it working because for the FE app there is no `wrangler.toml` file
