### ISSUE TITLE
Request: Install Newer Version of Wrangler by Default

### ISSUE THREAD

**Issue by CNX-Inc** [cloudflare/wrangler-action#366]
Noting, this might be something with my project (I'm not much of a node user but i have updated my `package.json` and `package-lock.json` files to no avail.

It seems as though the action installs an outdated wrangler by default, from my logs:
 `/usr/local/bin/npm i wrangler@3.90.0`

Currently I'm using Wrangler 4.14.1 (locally) and the older version seems to not like to deploy.

Here's how I've worked around the issue, but thought you all might want to update the default or maybe provide an `version: 4.14.1` option to `with:` 

Thanks!

```jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "data-worker"
          preCommands: |
            echo "*** pre commands ***"
            echo `pwd`
            npx wrangler --version
            npm install wrangler@latest
            echo "******"
```

**Comment by mamiu** [comment]
Had the same problem right now when trying to use the IMAGES binding.

**Comment by RobFaustLZ** [comment]
Following. All the Wrangler project initialization scripts have been updated to use `.jsonc` config files by default rather than the old `.toml` format. But, `.jsonc` isn't supported until Wrangler 3.91 and the default is currently set to 3.90.

**Comment by omkhar** [comment]
I presume there is a valid reason for not changing default behavior. Rather than invoking a manual installation, you can just pass `wranglerVersion` like this:
      
```
     - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        name: Deploy to Cloudflare (Production)
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "latest"
```
