### ISSUE TITLE
deployment-url not available for `versions upload ..` command

### ISSUE THREAD

**Issue by spelexander** [cloudflare/wrangler-action#371]
Given this example actions yaml config:
```yaml
      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions upload --config ./wrangler.json

      - name: Create deployment URL artifact
        run: |
          echo "${{ steps.deploy.outputs.deployment-url }}"
```

`steps.deploy.outputs.deployment-url` is missing.

The current advice from Cloudflare is to migrate to workers from pages. We currently deploy preview branches manually with pages, so that we can run tests on the branch in an action afterwards without a race condition. 

I am currently recreating branch deployments using Workers, to replace our current pages, which required `version upload ...` outputting:
```bash
Uploaded renewmap-workers-test (2.79 sec)
  Worker Version ID: 123456
  Version Preview URL: 123456.example.dev # <------ The thing I need in the build output
  
  To deploy this version to production traffic use the command wrangler versions deploy
  
  Changes to non-versioned settings (config properties 'logpush' or 'tail_consumers') take effect after your next deployment using the command wrangler versions deploy
  
  Changes to triggers (routes, custom domains, cron schedules, etc) must be applied with the command wrangler triggers deploy
  
🏁 Wrangler Action completed
```

Adding steps.deploy.outputs.deployment-url for versions upload would make things much easier here. Right now it looks like I have to parse the URL out of the output
