### ISSUE TITLE
Update wrangler to v4

### ISSUE THREAD

**Issue by CyberFlameGO** [cloudflare/wrangler-action#375]
The action seems out of date with the latest wrangler CLI version

**Comment by MonsignorEduardo** [comment]
Its uses the last of the [npm](https://www.npmjs.com/package/wrangler), if it using an older version use the `wranglerVersion` key 
example
```
 - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.23.0'
```

**Comment by tegarportier** [comment]
> Its uses the last of the [npm](https://www.npmjs.com/package/wrangler), if it using an older version use the `wranglerVersion` key example
> 
> ```
>  - name: Deploy to Cloudflare Workers
>         id: deploy
>         uses: cloudflare/wrangler-action@v3
>         with:
>           wranglerVersion: '4.23.0'
> ```

This works! Thank you! It should be in the readme since I got error due to different wrangler version.

**Comment by BaseMax** [comment]
I am going to change the following code in our github cicd:

```
      - name: 🚀 Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "packages/cfsite"
          command: deploy
```

to the following:

```
      - name: 📦 Install dependencies
        run: npm ci
        working-directory: packages/cfsite

      - name: 🚀 Deploy to Cloudflare Workers
        run: npx wrangler deploy
        working-directory: packages/cfsite
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
```
