### ISSUE TITLE
wrangler-action failing since wrangler 1.14.0 (EACCES: permission denied, mkdir)

### ISSUE THREAD

**Issue by mistarn** [cloudflare/wrangler-action#49]
The newest wrangler doesn't work with wrangler-action due to an unknown permission issue. I've told my Github Action to use `wranglerVersion: '1.13.0'` in the meantime to get it working again.
```
uses: cloudflare/wrangler-action@1.3.0
  with:
    apiToken: ${{ secrets.CF_API_TOKEN }}
    wranglerVersion: '1.13.0'
```

The error in question:
```
Using API Token authentication
/usr/local/bin/wrangler -> /usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

> @cloudflare/wrangler@1.14.0 postinstall /usr/local/lib/node_modules/@cloudflare/wrangler
> node ./install-wrangler.js

internal/fs/utils.js:269
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@cloudflare/wrangler/wrangler'
    at mkdirSync (fs.js:921:3)
    at Binary._getInstallDirectory (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/@cloudflare/binary-install/src/binary.js:52:7)
    at Binary.install (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/@cloudflare/binary-install/src/binary.js:78:22)
    at install (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:52:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/@cloudflare/wrangler/wrangler'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @cloudflare/wrangler@1.14.0 postinstall: `node ./install-wrangler.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @cloudflare/wrangler@1.14.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/workspace/.npm/_logs/2021-03-05T01_17_09_614Z-debug.log
```

**Comment by mistarn** [comment]
If it helps, I'm using the Flareact deploy template. Here's my full deploy.yml file:
```
name: Deploy
on:
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install
    - run: yarn build
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        wranglerVersion: '1.13.0'
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        IS_WORKER: true
```
