### ISSUE TITLE
Option for yarn instead of npm?

### ISSUE THREAD

**Issue by jasikpark** [cloudflare/wrangler-action#51]
I use yarn for managing my packages, is it possible to add a configuration that installs wrangler and all of the packages via yarn rather than the default npm, as it is now?

**Comment by amaitu** [comment]
The action appears to be build such that it doesn't have opinions on how you code should be built. So you can use yarn, you'd just need to do so in a step prior to calling the wrangler action. For example:

```
    steps:
      - uses: actions/checkout@master
      - name: Build site with yarn
        run: 'yarn build'
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}     
```
