### ISSUE TITLE
wrangler build fails with npm@7 workspace build; fails to find parent node_modules/.bin/*

### ISSUE THREAD

**Issue by olizilla** [cloudflare/wrangler-action#59]
Using the new npm@7 workspace (https://docs.npmjs.com/cli/v7/using-npm/workspaces)  monorepo feature and having a worker project in a subdir like `packages/a` with a custom build step in defined in the wrangler.toml like

```toml
type = "javascript"

[build]
command = "npm run build"
```
https://github.com/olizilla/wrangler-npm-workspace-test/blob/ed566f38cb40a1ea7265ceb803e0a95ada1cb8cf/packages/a/wrangler.toml#L8

and the package.json build script calls `webpack`

```json
  "scripts": {
    "build": "webpack"
  }
```

and the`wrangler-action` configured to use the subdir `packages/a` as the workingDir

```yaml
  deploy:
    name: Deploy worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - name: Publish worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/a'
```
https://github.com/olizilla/wrangler-npm-workspace-test/blob/ed566f38cb40a1ea7265ceb803e0a95ada1cb8cf/.github/workflows/publish.yml#L37-L41

fails, as npm can't find the `webpack` command. 

```console
Run cloudflare/wrangler-action@1.3.0
/usr/bin/docker run --name a33c1892afcf99f6a4cc5ad8cc44158b68845_8d1fcd --label 8a33c1 --workdir /github/workspace --rm -e npm_config_cache -e INPUT_APITOKEN -e INPUT_WORKINGDIRECTORY -e INPUT_APIKEY -e INPUT_EMAIL -e INPUT_ENVIRONMENT -e INPUT_WRANGLERVERSION -e INPUT_SECRETS -e INPUT_PRECOMMANDS -e INPUT_POSTCOMMANDS -e INPUT_PUBLISH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/wrangler-npm-workspace-test/wrangler-npm-workspace-test":"/github/workspace" 8a33c1:892afcf99f6a4cc5ad8cc44158b68845
Using API Token authentication
/usr/local/bin/wrangler -> /usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

> @cloudflare/wrangler@1.17.0 postinstall /usr/local/lib/node_modules/@cloudflare/wrangler
> node ./install-wrangler.js

Downloading release from https://workers.cloudflare.com/get-npm-wrangler-binary/1.17.0/x86_64-unknown-linux-musl
wrangler has been installed!
+ @cloudflare/wrangler@1.17.0
added 22 packages from 9 contributors in 1.811s
 Running npm run build

> a@1.0.0 build /github/workspace/packages/a
> webpack

sh: 1: webpack: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! a@1.0.0 build: `webpack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the a@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-07-07T14_01_26_044Z-debug.log
Error: Build failed! Status Code: 1
```

In a npm@7 workspace project, the command is installed in the root `node_modules/.bin/webpack` not in the subdir `packages/a/node_modules/.bin/webpack`. This action currently uses the [`node:12` docker image](https://github.com/cloudflare/wrangler-action/blob/60c377d0bf2e77762f44e9392c5c85e99f25fc4e/Dockerfile#L1) so my guess is that that the wrangler build command is running `npm run build` in the docker container, so npm@6 is used. 

Locally `wrangler publish` succeeds when `npm@7` is available, but fails with `npm@6` which is the default bundled with `node@12`.

A fix here would be to update the node docker image to `node:16` which bundles `npm@7`.

I've made a minimal test repo, that shows the problem https://github.com/olizilla/wrangler-npm-workspace-test
this build should pass: https://github.com/olizilla/wrangler-npm-workspace-test/runs/3009656412

**Comment by olizilla** [comment]
As a work around, i've forked the action and updated the Docker image as per #56 and updated my workflow to use that fork
```
      - name: Publish worker
        # workaround for https://github.com/cloudflare/wrangler-action/issues/59 to use node 16
        uses: web3-storage/wrangler-action@node16
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/api'
```

If anyone else has this issue, feel free to use that fork

```yaml
uses: web3-storage/wrangler-action@node16
```
or to avoid depending on a mutable reference, go for the sha

```yaml
uses: web3-storage/wrangler-action@78130c1d1e3ceb6ee3bb7613d7753431ce6bb479
```

from https://github.com/web3-storage/wrangler-action/pull/1
