### ISSUE TITLE
Action fails with: 'rustc' not found

### ISSUE THREAD

**Issue by fkettelhoit** [cloudflare/wrangler-action#60]
`wrangler-action@1.3.0` fails with the following error:

`Error: 'rustc' not found: cannot find binary path. Installation documentation can be found here: https://www.rust-lang.org/tools/install`

This is the workflow file that I used:

```yaml
name: Publish Cloudflare Worker (Dev)

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  publish:
    name: Publish Cloudflare Worker (Dev)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'some_dir/some_subdir'
```

Has the docker image perhaps been changed in a way that Rust is not properly installed anymore? As a workaround I have now switched to the following workflow, which works but is of course slower as wrangler first has to be installed:

```yaml
name: Publish Cloudflare Worker (Dev)

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  publish:
    name: Publish Cloudflare Worker (Dev)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        working-directory: some_dir/some_subdir
        run: cargo install wrangler && wrangler publish
```
