### ISSUE TITLE
feat: customize node version

### ISSUE THREAD

**Issue by Namchee** [cloudflare/wrangler-action#69]
## Overview

Currently, `cloudflare/wrangler-action` does not support NodeJS version outside v12. This will potentially cause issues with some dependencies as some require a newer version of NodeJS.

To adhere to this issue, I think we can implement a new property `node-version` just like how [actions/setup-node](https://github.com/actions/setup-node) implemented it.

**Comment by jasoncabot** [comment]
If you need to use this action with version 16 of node, you can change the version of the action you're using from `cloudflare/wrangler-action@1.3.0` to `cloudflare/wrangler-action@next` which builds from the `node:16` base image:

* PR: https://github.com/cloudflare/wrangler-action/pull/56
* Release: https://github.com/cloudflare/wrangler-action/releases/tag/next

**Comment by aalvarado** [comment]
Node 12 is deprecated making the `next` branch the only one that currently doesn't error out. https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by prestonp** [comment]
Could we reopen this? We would like to customize node version without having to fork and tweak the Dockerfile.

We have a use case where we use wrangler-action as part of a large monorepo (using yarn workspaces) with our root package.json specifying 

```
  "engines": {
    "node": ">= 18.x.x"
  },
```

Our Github action file roughly looks like this

```
- name: setup Node
  uses: actions/setup-node@v3
  with:
    node-version: "18.15"
    cache: "yarn"

- name: Publish
  uses: cloudflare/wrangler-action@2.0.0
  with:
    apiToken: <REDACTED>
    preCommands: yarn install --frozen-lockfile --non-interactive
    workingDirectory: "services/workers"
```

The yarn install fails because of the node engine incompatibility

```
error monorepo@0.97.0: The engine "node" is incompatible with this module. Expected version ">= 18.x.x". Got "16.20.1"
```
