### ISSUE TITLE
Secrets uploaded with trailing `\n`

### ISSUE THREAD

**Issue by gerukin** [cloudflare/wrangler-action#75]
Hi all and thank you for the awesome job with the Cloudflare ecosystem. 🙇‍♂️

Looks like there might be a bit of a problem with Wrangler Action `2.0` (I do not recall having had this issue with the previous version, which was using the same configuration and the same secret values).

Given this configuration:
```yaml
# ...
uses: cloudflare/wrangler-action@2.0.0
  with:
    apiToken: ${{ secrets.CF_API_TOKEN }}
    secrets: |
      SECRET_A
      SECRET_B
    env:
      SECRET_A: ${{ secrets.A }}
      SECRET_B: ${{ secrets.B }}
```

Gives you secrets like this in the worker:
```
SECRET_A="valueA\n"
SECRET_B="valueB\n"
```

Please note that the value of the Github secrets had not changed, but just to be safe, I tried to re-enter them, making extra certain that no trailing `\n` or line feed is there, and I still have the issue. The `CF_API_TOKEN` is also working fine so I assume it isn't a new problem with Github secrets.

When I upload the secrets manually using wrangler CLI it works fine. 🎉
I just can't do it from here without having the `\n` appended to everything. 🤷‍♂️
