### ISSUE TITLE
env parameter does not work for secrets

### ISSUE THREAD

**Issue by dhrubabasu** [cloudflare/wrangler-action#76]
Should be uploading secrets for script `my-worker-test`, not `my-worker`

```yml
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: publish --env ${{ github.events.inputs.environment }}
          secrets: |
            secret1
            secret2
        env:
          USER: root
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secret1: ${{ secrets.secret1 }}
          secret2: ${{ secrets.secret2 }}
```

```
Using API Token authentication
 ⛅️ wrangler 2.0.5 
-------------------
🌀 Creating the secret for script my-worker
✨ Success! Uploaded secret secret1
 ⛅️ wrangler 2.0.5 
-------------------
🌀 Creating the secret for script my-worker
✨ Success! Uploaded secret secret2
$ Running: wrangler publish --env test
 ⛅️ wrangler 2.0.5 
-------------------
Running custom build: npm run build
> my-worker@0.0.0 build
> worktop build src/index.ts
  build/index.mjs  12.5kb
⚡ Done in 8ms
Uploaded my-worker-test (0.54 sec)
Published my-worker-test (0.31 sec)
```

**Comment by Crisfole** [comment]
You should be using the `environment` input to the command instead! 😄 

```toml
with:
  ...
  environment: ${{ github.events.inputs.environment }}
```

**Comment by dhrubabasu** [comment]
Ah, seems like you need to do both:

```
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: publish --env ${{ github.events.inputs.environment }}
          environment: ${{ github.events.inputs.environment }}
          secrets: |
            secret1
            secret2
        env:
          USER: root
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secret1: ${{ secrets.secret1 }}
          secret2: ${{ secrets.secret2 }}
```

`publish` doesn't read from the `environment` input but `secrets` do
