### ISSUE TITLE
How do I get the URL after a `pages` preview deployment?

### ISSUE THREAD

**Issue by LittleSound** [cloudflare/wrangler-action#81]
I want to use the preview deployment of `pages` in `PR` and add `URL` to `environment`, but I don't know how to get the "Preview URL", it's not written in the documentation.

## Desired effect

```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: dev-preview
      url: ${{ steps.builddeploy.outputs.web_app_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish --project-name=example
```

When this CI is run you will see:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/19204772/185340152-43a93b14-b83b-4e90-a5e8-d5d071cbb692.png">

**Comment by microHoffman** [comment]
Is there any way how to do this currently? Given that cloudflare also trims the branch name alias deploy url after certain characters, this is must have for us to be able to display deployed preview url in the PR comments. Thanks!

**Comment by Erisa** [comment]
You can use Pages action: https://github.com/cloudflare/pages-action

**Comment by polaroidkidd** [comment]
so the pages action will deprecated at some point in the future - https://github.com/cloudflare/pages-action/issues/131#issuecomment-2203648174

How would we do this with the wrangler-action?

**Comment by Erisa** [comment]
For what its worth, I don't work at Cloudflare anymore.

But I do see @polaroidkidd that this action now has outputs for deployment URLs: https://github.com/cloudflare/wrangler-action?tab=readme-ov-file#using-the-deployment-url-output-variable

There is an example on that README which shows how you access it through `.outputs`:

```yaml
- name: Deploy
  id: deploy
  uses: cloudflare/wrangler-action@v3
  with:
    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    command: pages deploy --project-name=example

- name: print deployment-url
  env:
    DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
  run: echo $DEPLOYMENT_URL
```
