### ISSUE TITLE
/bin/sh: 1: cargo: not found

### ISSUE THREAD

**Issue by gagan-suie** [cloudflare/wrangler-action#82]
https://github.com/cloudflare/workers-rs

I created a template project from the repo above.
I keep getting this error:

```
Running custom build: cargo install -q worker-build && worker-build --release
/bin/sh: 1: cargo: not found

✘ [ERROR] Command failed with exit code 127: cargo install -q worker-build && worker-build --release
```

Here is my repository.
https://github.com/CodeCrowCorp/infinibuild-api

```
  deploy:
    name: Deploy to Cloudflare Workers
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          WORKERS_RS_VERSION: ${{ secrets.WORKERS_RS_VERSION }}
```
