### ISSUE TITLE
Get deployment url in the next step

### ISSUE THREAD

**Issue by harshbaz** [cloudflare/wrangler-action#90]
```
- name: Deploy preview build
        id: cf_pages_deploy_dev
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_DEPLOY_API_TOKEN }}
          command: pages publish --project-name=test
        env:
          CLOUDFLARE_ACCOUNT_ID: "xxx"
      - name: Echo dev output
        run: echo '${{join(steps.cf_pages_deploy_dev.outputs.*, '\n')}}'
```

How do I get the url of the deployed build in the next step?
